### ISSUE TITLE
Reseting timer on removed alt crashes

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#79]
Alt character was in an NPC corp, removed from the ACL, then went to reset the timer, and it crashed.

Environment:

Request Method: GET
Request URL: http://auth.eveuniversity.org/whctools/staff/action/2122754078/reset

Django Version: 4.2.16
Python Version: 3.11.10
Installed Applications:
['allianceauth',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_celery_beat',
 'solo',
 'bootstrapform',
 'django_bootstrap5',
 'sortedm2m',
 'esi',
 'allianceauth.framework',
 'allianceauth.authentication',
 'allianceauth.services',
 'allianceauth.eveonline',
 'allianceauth.groupmanagement',
 'allianceauth.notifications',
 'allianceauth.thirdparty.navhelper',
 'allianceauth.analytics',
 'allianceauth.menu',
 'allianceauth.theme',
 'allianceauth.custom_css',
 'eunicore',
 'eunicore.theme.slate',
 'allianceauth.permissions_tool',
 'allianceauth.hrapplications',
 'allianceauth.services.modules.discord',
 'allianceauth.services.modules.mumble',
 'aasrp',
 'afat',
 'blacklist',
 'buybackprogram',
 'celeryanalytics',
 'eveuniverse',
 'fittings',
 'fleetpings',
 'freight',
 'groupassign',
 'memberaudit',
 'memberaudit_securegroups',
 'moonstuff',
 'opcalendar',
 'package_monitor',
 'securegroups',
 'structures',
 'structuretimers',
 'taskmonitor',
 'whctools']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'allianceauth.authentication.middleware.UserSettingsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/allianceauth/authentication/decorators.py", line 50, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allianceauth/.local/lib/python3.11/site-packages/whctools/views.py", line 359, in reset
    member_application.eve_character.character_ownership.user,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ^

Exception Type: RelatedObjectDoesNotExist at /whctools/staff/action/2122754078/reset
Exception Value: EveCharacter has no character_ownership.

**Comment by lynkfox** [comment]
That... Looks like also it got removed from the user? Ie they deleted the
char from auth
